/** Generated by scripts/gen-doc-catalog.py. Do not edit by hand. */
export const REGIONAL_DOCUMENT_COVERAGE = {
  sourceRecords: 964,
  saldoRecords: 106,
  saldoMunicipalities: 70,
  counties: ['York', 'Cumberland', 'Dauphin', 'Lancaster'] as const,
} as const;
