/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AcquireRouteImport } from './routes/acquire'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as MinutesRouteImport } from './routes/minutes'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as ZoningRouteImport } from './routes/zoning'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ParcelsIdRouteImport } from './routes/parcels.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquireRoute = AcquireRouteImport.update({
  id: '/acquire',
  path: '/acquire',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MinutesRoute = MinutesRouteImport.update({
  id: '/minutes',
  path: '/minutes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoningRoute = ZoningRouteImport.update({
  id: '/zoning',
  path: '/zoning',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelsIdRoute = ParcelsIdRouteImport.update({
  id: '/parcels/$id',
  path: '/parcels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/acquire': typeof AcquireRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/guide': typeof GuideRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/minutes': typeof MinutesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/workspace': typeof WorkspaceRoute
  '/zoning': typeof ZoningRoute
  '/api/health': typeof ApiHealthRoute
  '/parcels/$id': typeof ParcelsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/acquire': typeof AcquireRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/guide': typeof GuideRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/minutes': typeof MinutesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/workspace': typeof WorkspaceRoute
  '/zoning': typeof ZoningRoute
  '/api/health': typeof ApiHealthRoute
  '/parcels/$id': typeof ParcelsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/acquire': typeof AcquireRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/guide': typeof GuideRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/minutes': typeof MinutesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/workspace': typeof WorkspaceRoute
  '/zoning': typeof ZoningRoute
  '/api/health': typeof ApiHealthRoute
  '/parcels/$id': typeof ParcelsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/acquire'
    | '/dashboard'
    | '/documents'
    | '/guide'
    | '/insights'
    | '/login'
    | '/map'
    | '/minutes'
    | '/notifications'
    | '/privacy'
    | '/subscription'
    | '/terms'
    | '/workspace'
    | '/zoning'
    | '/api/health'
    | '/parcels/$id'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/acquire'
    | '/dashboard'
    | '/documents'
    | '/guide'
    | '/insights'
    | '/login'
    | '/map'
    | '/minutes'
    | '/notifications'
    | '/privacy'
    | '/subscription'
    | '/terms'
    | '/workspace'
    | '/zoning'
    | '/api/health'
    | '/parcels/$id'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/acquire'
    | '/dashboard'
    | '/documents'
    | '/guide'
    | '/insights'
    | '/login'
    | '/map'
    | '/minutes'
    | '/notifications'
    | '/privacy'
    | '/subscription'
    | '/terms'
    | '/workspace'
    | '/zoning'
    | '/api/health'
    | '/parcels/$id'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AcquireRoute: typeof AcquireRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  GuideRoute: typeof GuideRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MinutesRoute: typeof MinutesRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TermsRoute: typeof TermsRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ZoningRoute: typeof ZoningRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ParcelsIdRoute: typeof ParcelsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquire': {
      id: '/acquire'
      path: '/acquire'
      fullPath: '/acquire'
      preLoaderRoute: typeof AcquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minutes': {
      id: '/minutes'
      path: '/minutes'
      fullPath: '/minutes'
      preLoaderRoute: typeof MinutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zoning': {
      id: '/zoning'
      path: '/zoning'
      fullPath: '/zoning'
      preLoaderRoute: typeof ZoningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcels/$id': {
      id: '/parcels/$id'
      path: '/parcels/$id'
      fullPath: '/parcels/$id'
      preLoaderRoute: typeof ParcelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AcquireRoute: AcquireRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  GuideRoute: GuideRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MinutesRoute: MinutesRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  SubscriptionRoute: SubscriptionRoute,
  TermsRoute: TermsRoute,
  WorkspaceRoute: WorkspaceRoute,
  ZoningRoute: ZoningRoute,
  ApiHealthRoute: ApiHealthRoute,
  ParcelsIdRoute: ParcelsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
